version: '3.9'

services:
#  postgres:
#    container_name: postgres
#    image: postgres:15
#    ports:
#      - "5432:5432"
#    restart: always
#    env_file: ./postgres/.env
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#      - ./postgres/initdb.d:/docker-entrypoint-initdb.d:rw
#    networks:
#      - infra_network

  redis:
    container_name: redis
    image: redis:7.0.11
    ports:
      - "6479:6479"
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"
    env_file: ./redis/.env
    volumes:
      - redis_data:/data:rw
      - ./redis/etc/redis.conf:/etc/redis.conf:rw
    command: redis-server /etc/redis.conf
    network_mode: host

#    networks:
#      - infra_network

  redis-slave:
    image: redis:7.0.11
    hostname: redis-slave
    volumes:
      - redis_slave:/data
      - ./redis/etc/slave.conf:/etc/slave.conf:rw
    env_file: ./redis/.env
    ports:
      - "6479:6479"
    command: redis-server /etc/slave.conf
    network_mode: host
#    networks:
#      - infra_network

volumes:
#  postgres_data:
  redis_data:
  redis_insight_data:
  redis_slave:

networks:
  infra_network:
